### ISSUE TITLE
Unable to find type [BuildActionType]. Make sure that the assembly that contains this type is loaded

### ISSUE THREAD

**Issue by hasithapg** [piotrekh/dbup-add-migration#2]
Hi,

I am getting the following error when trying to execute the command;

Add-Migration "MyFirstMigration"

PM> Add-Migration "MyFirstMigration"
Add-Migration : Unable to find type [BuildActionType]. Make sure that the assembly that contains this type is loaded.
At line:1 char:1
+ Add-Migration "MyFirstMigration"
+ ~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (BuildActionType:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound

Any clues?

Thanks in advance.

Hasitha

**Comment by piotrekh** [comment]
Hi Hasitha,

Please check if you have Powershell 5 installed, that might be the issue (run `$PSVersionTable.PSVersion`).

**Comment by hasithapg** [comment]
Thanks piotrekh, Upgraded to V5 and worked like a charm!!!
